// Countries
export const countries = [
	{name: 'India', code: 'IN', flag: '🇮🇳'},
	{name: 'United States', code: 'US', flag: '🇺🇸'},
	{name: 'United Kingdom', code: 'GB', flag: '🇬🇧'},
	{name: 'Canada', code: 'CA', flag: '🇨🇦'},
	{name: 'Australia', code: 'AU', flag: '🇦🇺'},
	{name: 'Germany', code: 'DE', flag: '🇩🇪'},
	{name: 'France', code: 'FR', flag: '🇫🇷'},
	{name: 'Japan', code: 'JP', flag: '🇯🇵'},
	{name: 'China', code: 'CN', flag: '🇨🇳'},
	{name: 'Singapore', code: 'SG', flag: '🇸🇬'},
	{name: 'United Arab Emirates', code: 'AE', flag: '🇦🇪'},
	{name: 'Switzerland', code: 'CH', flag: '🇨🇭'},
	{name: 'Netherlands', code: 'NL', flag: '🇳🇱'},
	{name: 'Sweden', code: 'SE', flag: '🇸🇪'},
	{name: 'Norway', code: 'NO', flag: '🇳🇴'},
	{name: 'Denmark', code: 'DK', flag: '🇩🇰'},
	{name: 'Finland', code: 'FI', flag: '🇫🇮'},
	{name: 'Belgium', code: 'BE', flag: '🇧🇪'},
	{name: 'Ireland', code: 'IE', flag: '🇮🇪'},
	{name: 'New Zealand', code: 'NZ', flag: '🇳🇿'},
	{name: 'Russia', code: 'RU', flag: '🇷🇺'},
	{name: 'Poland', code: 'PL', flag: '🇵🇱'},
	{name: 'Austria', code: 'AT', flag: '🇦🇹'},
	{name: 'Hungary', code: 'HU', flag: '🇭🇺'},
	{name: 'Albania', code: 'AL', flag: '🇦🇱'},
	{name: 'Antigua and Barbuda', code: 'AG', flag: '🇦🇬'},
	{name: 'Argentina', code: 'AR', flag: '🇦🇷'},
	{name: 'Bahrain', code: 'BH', flag: '🇧🇭'},
	{name: 'Belarus', code: 'BY', flag: '🇧🇾'},
	{name: 'Bosnia and Herzegovina', code: 'BA', flag: '🇧🇦'},
	{name: 'Brazil', code: 'BR', flag: '🇧🇷'},
	{name: 'Bulgaria', code: 'BG', flag: '🇧🇬'},
	{name: 'Croatia', code: 'HR', flag: '🇭🇷'},
	{name: 'Cyprus', code: 'CY', flag: '🇨🇾'},
	{name: 'Czech Republic', code: 'CZ', flag: '🇨🇿'},
	{name: 'Dominica', code: 'DM', flag: '🇩🇲'},
	{name: 'Estonia', code: 'EE', flag: '🇪🇪'},
	{name: 'Greece', code: 'GR', flag: '🇬🇷'},
	{name: 'Grenada', code: 'GD', flag: '🇬🇩'},
	{name: 'Indonesia', code: 'ID', flag: '🇮🇩'},
	{name: 'Israel', code: 'IL', flag: '🇮🇱'},
	{name: 'Italy', code: 'IT', flag: '🇮🇹'},
	{name: 'Kenya', code: 'KE', flag: '🇰🇪'},
	{name: 'Kosovo', code: 'XK', flag: '🇽🇰'},
	{name: 'Kuwait', code: 'KW', flag: '🇰🇼'},
	{name: 'Latvia', code: 'LV', flag: '🇱🇻'},
	{name: 'Lithuania', code: 'LT', flag: '🇱🇹'},
	{name: 'Macedonia', code: 'MK', flag: '🇲🇰'},
	{name: 'Malaysia', code: 'MY', flag: '🇲🇾'},
	{name: 'Mexico', code: 'MX', flag: '🇲🇽'},
	{name: 'Moldova', code: 'MD', flag: '🇲🇩'},
	{name: 'Montenegro', code: 'ME', flag: '🇲🇪'},
	{name: 'Montserrat', code: 'MS', flag: '🇲🇸'},
	{name: 'Nigeria', code: 'NG', flag: '🇳🇬'},
	{name: 'Oman', code: 'OM', flag: '🇴🇲'},
	{name: 'Pakistan', code: 'PK', flag: '🇵🇰'},
	{name: 'Philippines', code: 'PH', flag: '🇵🇭'},
	{name: 'Portugal', code: 'PT', flag: '🇵🇹'},
	{name: 'Qatar', code: 'QA', flag: '🇶🇦'},
	{name: 'Romania', code: 'RO', flag: '🇷🇴'},
	{name: 'Saint Kitts and Nevis', code: 'KN', flag: '🇰🇳'},
	{name: 'Saint Lucia', code: 'LC', flag: '🇱🇨'},
	{name: 'Saint Vincent and the Grenadines', code: 'VC', flag: '🇻🇨'},
	{name: 'Saudi Arabia', code: 'SA', flag: '🇸🇦'},
	{name: 'Serbia', code: 'RS', flag: '🇷🇸'},
	{name: 'Slovakia', code: 'SK', flag: '🇸🇰'},
	{name: 'Slovenia', code: 'SI', flag: '🇸🇮'},
	{name: 'South Africa', code: 'ZA', flag: '🇿🇦'},
	{name: 'South Korea', code: 'KR', flag: '🇰🇷'},
	{name: 'Spain', code: 'ES', flag: '🇪🇸'},
	{name: 'Taiwan', code: 'TW', flag: '🇹🇼'},
	{name: 'Thailand', code: 'TH', flag: '🇹🇭'},
	{name: 'Trinidad and Tobago', code: 'TT', flag: '🇹🇹'},
	{name: 'Turkey', code: 'TR', flag: '🇹🇷'},
	{name: 'Vietnam', code: 'VN', flag: '🇻🇳'}
] as const
